version: '3.7'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=logs
      - POSTGRES_PASSWORD=logs
      - POSTGRES_DB=logs
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
